language: ch
pipeline:
- name: HFTransformersNLP
  model_name: bert
  model_weights: bert-base-chinese
  cache_dir: /tmp
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: DIETClassifier
  epochs: 50
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 50
- name: MappingPolicy
- name: FormPolicy
